### ISSUE TITLE
Error Running Example Code

### ISSUE THREAD

**Issue by dylanasimov** [dgretton/pyhamilton#5]
I'm trying to run a version of the single_ch_aspirate_dispense.py example method and was thrown this error:

Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Hamilton\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Hamilton\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Hamilton\AppData\Local\Programs\Python\Python36\lib\site-packages\pyhamilton\interface.py", line 135, in run_hamilton_process
    clr.AddReference(os.path.join(OEM_STAR_PATH, 'RunHSLExecutor'))
System.IO.FileNotFoundException: Unable to find assembly 'C:\Users\Hamilton\AppData\Local\Programs\Python\Python36\lib\site-packages\pyhamilton\STAR-OEM\RunHSLExecutor'.
   at Python.Runtime.CLRModule.AddReference(String name)

Was wondering if there was any advice on how to rectify this.

**Comment by cekarius** [comment]
I have the same problem. But I tried it with Win10. Could this be the reason? The readme says it's compatible with XP or Win7

**Comment by dylanasimov** [comment]
> I have the same problem. But I tried it with Win10. Could this be the reason? The readme says it's compatible with XP or Win7

Thanks for the input. I also tried running it on a computer with Win10, but I wasn't sure if the error was related to the OS.

**Comment by jendas1** [comment]
I think the problem might be related to having x64 version of python3 installed while hamilton software was built for x86 (see https://stackoverflow.com/questions/13259617/python-for-net-unable-to-find-assembly-error comment under accepted answer).

After installing x86 version of python3, I get a different error though.
```
 File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyhamilton\interface.py", line 140, in run_hamilton_process
    raise RuntimeError('RunHSLExecutor DLLs successfully located, but an internal '
RuntimeError: RunHSLExecutor DLLs successfully located, but an internal error prevented import as a CLR module. You might be missing the standard Hamilton software suite HSL executables, their DLLs may not be registered with Windows, or they may not be located in the expected system directory.
```
I am also running on Windows 10.

**Comment by stefangolas** [comment]
@jendas1 make sure to install the executables that are now in the /bin folder on the repository
